project:
  type: website

website:
  title: UNICEF AI4D Poverty Mapping Project
  navbar:
    title: false
    background: primary

  sidebar:
    contents:
      - href: index.qmd
        text: Main
      - href: about.qmd
        text: About
      - href: progress.qmd
        text: Progress
      - section: "Data Preparation (DHS)"
        contents:
          - test-notebooks/explore_dhs.ipynb
          - test-notebooks/explore_kh_dhs.ipynb
          - test-notebooks/explore_mm_dhs.ipynb
          - test-notebooks/explore_ph_dhs.ipynb
          - test-notebooks/explore_tl_dhs.ipynb
      - section: "Data Preparation (Ookla)"
        contents:
          - test-notebooks/explore_ookla.ipynb
          - test-notebooks/explore_ookla_data.ipynb
          - test-notebooks/explore_kh_ookla.ipynb
          - test-notebooks/explore_mm_ookla.ipynb
          - test-notebooks/explore_ph_ookla.ipynb
          - test-notebooks/explore_tl_ookla.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



