project:
  type: website

website:
  title: UNICEF AI4D Poverty Mapping Project
  navbar:
    title: false
    background: primary

  sidebar:
    contents:
      - href: index.qmd
        text: Main
      - href: about.qmd
        text: About
      - href: progress.qmd
        text: Progress
      - section: "Sprint 1"
        contents:
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_ph.ipynb
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_kh.ipynb
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_mm.ipynb
          - href: notebooks/2023-01-17-initial-model-ph-mm-tl-kh/model_tl.ipynb


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



