buffer_side_length: 4.0
clust_rad: 2000
country: tl
crs: '4683'
data_dir: tl
dhs_folder: dhs_tl
dhs_geo_zip_folder: TLGE71FL
multiprocess: false
no_samples: 60
osm_country: tl
osm_folder: osm_tl
osm_pbf_filename: east-timor-latest.osm.pbf
osm_shp_filename: east-timor-latest-free.shp
random_sample: false
random_seed: 42
repo_path: ../test_data/inputs
sample: false
save_path: ../test_data/test_outputs/osm
use_pbf: false
